# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Abcent-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Abcent-Swift
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
end
